spring.application.name=heladix-backend
spring.datasource.url=jdbc:postgresql://localhost:5433/heladix
spring.datasource.username=heladix
spring.datasource.password=heladix_dev

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
